/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "apaocyrnacopmwuygaya"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwYW9jeXJuYWNvcG13dXlnYXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDk1MzcsImV4cCI6MjA3MTI4NTUzN30.Jxdb-zJvi2U00kWxe2eSodg0NbmhSpWwX6-f1cA_gnY"

// Helper functions for Supabase configuration checking
export const isSupabaseConfigured = (): boolean => {
  return !!(projectId && publicAnonKey && projectId !== "your-project-id" && publicAnonKey !== "your-anon-key");
}

export const isDevelopmentMode = (): boolean => {
  // Check if we're in development mode based on various indicators
  const isDev = 
    typeof window !== 'undefined' && 
    (window.location.hostname === 'localhost' || 
     window.location.hostname === '127.0.0.1' || 
     window.location.hostname.includes('preview') ||
     !isSupabaseConfigured());
  
  return isDev;
}